apiVersion: v1
kind: Service
metadata:
  name: knife
  labels:
    app: knife
spec:
  type: LoadBalancer
  ports:
    - name: knife
      protocol: TCP
      port: 5100
      targetPort: 5100
  selector:
    app: knife
